title: "Blog and Note of Nurul Imam"
subtitle: "Just a note about me, music, computer, internet, and web design"

author:
  name: Nurul Imam
  uri: http://www.nurulimam.com/
  email: me@nurulimam.com

theme: simple

disqus_short_name: nurulimam

cache: false

content: content

google_analytics_code: "UA-27943554-1"